### PR TITLE
Add Table of Contents, Contributing and License to README

### PR DESCRIPTION
**Pull request by OmerMohideen**
This pull request aims to improve the README by introducing a Table of Contents for easier navigation, a straightforward contribution message inviting users to open issues or submit pull requests, and a clear License section specifying the terms for code usage, modification, and distribution.

Changes proposed in this PR:

1. **Table of Contents**: Organize README sections for quick reference.
2. **Contribution Message**: Simplify the contribution message to encourage users to open issues or submit pull requests for bug fixes or feature requests.
3. **License Section**: Clearly define the project's license for transparent code usage, modification, and distribution.

### CODE REVIEW

**Comment by aminbagheridev** [comment]
LGTM merged

**Review by aminbagheridev — APPROVED** [review]

**Comment by OmerMohideen** [comment]
should we stick to conventional commits or the standard

**Comment by aminbagheridev** [comment]
Not sure what you mean by conventional vs standard

**Comment by OmerMohideen** [comment]
Conventional Commits:
- Follows a format like "type(scope): description", where "type" specifies the nature of change (e.g., feat for feature, fix for bug fix), "scope" indicates the affected component, and "description" briefly describes the change.

Standard: 
- Follows a format like "Update README.md", just the normal way of writing commit messages.

**Comment by aminbagheridev** [comment]
Got ya.

As long as the individual commits are smaller in length, we don't need to make them super detailed. 

A simple sentence to explain what the commit has done is fine.

If the commit is much larger, then it makes sense to follow the more conventional style you had mentioned.

**Pull request merged**
